/* Generated By:JavaCC: Do not edit this line. JSParserConstants.java */
package roland.javascript;

public interface JSParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int ABSTRACT = 8;
  int BOOLEAN = 9;
  int BREAK = 10;
  int BYTE = 11;
  int CASE = 12;
  int CATCH = 13;
  int CHAR = 14;
  int CLASS = 15;
  int CONST = 16;
  int CONTINUE = 17;
  int _DEFAULT = 18;
  int DELETE = 19;
  int DO = 20;
  int DOUBLE = 21;
  int ELSE = 22;
  int EXTENDS = 23;
  int FINAL = 24;
  int FINALLY = 25;
  int FLOAT = 26;
  int FOR = 27;
  int FUNCTION = 28;
  int GOTO = 29;
  int IF = 30;
  int IMPLEMENTS = 31;
  int IMPORT = 32;
  int IN = 33;
  int INSTANCEOF = 34;
  int INT = 35;
  int INTERFACE = 36;
  int LONG = 37;
  int NATIVE = 38;
  int NEW = 39;
  int PACKAGE = 40;
  int PRIVATE = 41;
  int PROTECTED = 42;
  int PUBLIC = 43;
  int RETURN = 44;
  int SHORT = 45;
  int STATIC = 46;
  int SUPER = 47;
  int SWITCH = 48;
  int SYNCHRONIZED = 49;
  int THIS = 50;
  int THROW = 51;
  int THROWS = 52;
  int TRANSIENT = 53;
  int TRY = 54;
  int TYPEOF = 55;
  int VAR = 56;
  int VOID = 57;
  int VOLATILE = 58;
  int WHILE = 59;
  int WITH = 60;
  int INTEGER_LITERAL = 61;
  int DECIMAL_LITERAL = 62;
  int HEX_LITERAL = 63;
  int OCTAL_LITERAL = 64;
  int FLOATING_POINT_LITERAL = 65;
  int EXPONENT = 66;
  int STRING_LITERAL = 67;
  int ESCAPE_SEQUENCE = 68;
  int BOOLEAN_LITERAL = 69;
  int NULL_LITERAL = 70;
  int IDENTIFIER = 71;
  int LETTER = 72;
  int DIGIT = 73;
  int LPAREN = 74;
  int RPAREN = 75;
  int LBRACE = 76;
  int RBRACE = 77;
  int LBRACKET = 78;
  int RBRACKET = 79;
  int SEMICOLON = 80;
  int COMMA = 81;
  int ASSIGN = 82;
  int GT = 83;
  int LT = 84;
  int BANG = 85;
  int TILDE = 86;
  int HOOK = 87;
  int COLON = 88;
  int DOT = 89;
  int EQ = 90;
  int LE = 91;
  int GE = 92;
  int NE = 93;
  int SC_OR = 94;
  int SC_AND = 95;
  int INCR = 96;
  int DECR = 97;
  int PLUS = 98;
  int MINUS = 99;
  int STAR = 100;
  int SLASH = 101;
  int BIT_AND = 102;
  int BIT_OR = 103;
  int XOR = 104;
  int REM = 105;
  int LSHIFT = 106;
  int RSIGNEDSHIFT = 107;
  int RUNSIGNEDSHIFT = 108;
  int SC_ORASSIGN = 109;
  int SC_ANDASSIGN = 110;
  int PLUSASSIGN = 111;
  int MINUSASSIGN = 112;
  int STARASSIGN = 113;
  int SLASHASSIGN = 114;
  int BIT_ANDASSIGN = 115;
  int BIT_ORASSIGN = 116;
  int XORASSIGN = 117;
  int REMASSIGN = 118;
  int LSHIFTASSIGN = 119;
  int RSIGNEDSHIFTASSIGN = 120;
  int RUNSIGNEDSHIFTASSIGN = 121;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"function\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"in\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"try\"",
    "\"typeof\"",
    "\"var\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"with\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<ESCAPE_SEQUENCE>",
    "<BOOLEAN_LITERAL>",
    "\"null\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\".\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"||=\"",
    "\"&&=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
  };

}
